name: Build and Push to GHCR

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and Push the Image to GHCR
        run: |
          docker login ghcr.io -user phatthanaphong --passwork-stdin ${{secrets.CIKEY}}
          docker build -t ghcr.io/phatthanaphong/languageprediction:latest .
          docker push ghcr.io/phatthanaphong/languageprediction:latest
